import java.util.ArrayList;
import java.util.List;

/**
 * The Java topics the game covers, and whether the player has met them.
 *
 * A topic counts as learned once a mission teaching it has been fully
 * completed, so this index is earned rather than declared.
 */
public class KnowledgeIndex {

    /**
     * campaign | topic | definition | why it matters in security
     *
     * A topic name must match a willLearn entry on at least one mission
     * exactly, because that is what ticks it. CheckAll enforces both
     * directions: every mission ticks at least one topic here, and once a
     * campaign is complete every topic listed for it has been taught.
     */
    private static final String[][] TOPICS = {
        {"0", "JVM",
         "The Java Virtual Machine. Runs compiled bytecode on any system.",
         "One .class file runs anywhere - for your tools and for malware."},
        {"0", "JDK",
         "The Java Development Kit: the compiler plus everything to run code.",
         "A compiler on a server is a tool an attacker can use too."},
        {"0", "main method",
         "Where a Java program starts running.",
         "Reading any program, suspicious or not, starts at its entry point."},
        {"0", "System.out.println",
         "Prints one line of text to the screen.",
         "Every tool reports its findings somehow. This is the simplest way."},
        {"0", "javac",
         "The compiler. Turns .java source into .class bytecode.",
         "Every mistake javac catches is one that never reaches production."},
        {"0", "Comments",
         "Notes in the source that Java ignores: // and /* */.",
         "Code says what. Only a comment can say why a check exists."},
        {"0", "Semicolons",
         "Mark where a statement ends. Line breaks do not.",
         "The error points at the next line. Knowing why saves the hunt."},
        {"0", "print vs println",
         "print stays on the line. println moves to the next one.",
         "Reports other tools parse must be laid out exactly."},
        {"0", "Escape sequences",
         "\\n, \\t and \\\" - characters you cannot type directly.",
         "Injected newlines and quotes are how log forgery works."},
        {"0", "Reading compiler errors",
         "File, line, message, and a caret pointing at the problem.",
         "Reading errors calmly is most of debugging."},
        {"0", "Producing exact output",
         "Output that matches character for character.",
         "One stray space breaks the tool that reads your report."},

        {"1", "Variables",
         "A named box holding one value of a fixed type.",
         "You cannot check a value you have not kept hold of."},
        {"1", "int",
         "The type that holds whole numbers.",
         "Failure counts, ports and clearance levels are all ints."},
        {"1", "String",
         "The type that holds text.",
         "Usernames, addresses and log lines are all Strings."},
        {"1", "Reassignment",
         "Putting a new value in a box that already exists.",
         "Every counter a detection rule keeps is reassigned constantly."},
        {"1", "boolean",
         "Holds true or false.",
         "Allowed or denied. Patched or not. No third answer."},
        {"1", "double",
         "The type that holds numbers with a decimal point.",
         "Severity scores stored as ints lose the part that ranks them."},
        {"1", "char",
         "Exactly one character, written in single quotes.",
         "Log levels and permission flags are single characters."},
        {"1", "Naming rules",
         "What Java allows a name to be, and what it forbids.",
         "Code you cannot read quickly is code you run on trust."},
        {"1", "final",
         "Marks a value that can never be reassigned.",
         "A threshold typed in five places will be wrong in one."},
        {"1", "Arithmetic operators",
         "+ - * / on numbers, with * and / before + and -.",
         "Risk scores are arithmetic. Wrong order, wrong priorities."},
        {"1", "Integer division",
         "int divided by int gives an int. The fraction is thrown away.",
         "Silent data loss: no crash, a believable wrong number."},
        {"1", "The remainder operator",
         "% gives what is left over after dividing.",
         "Finds what a division discarded, like unassigned alerts."},
        {"1", "Compound assignment",
         "+=, -=, *= and /= change a variable using its own value.",
         "Running totals across hosts are built this way."},
        {"1", "++",
         "Adds one to a variable. -- takes one away.",
         "The heart of every counting rule."},
        {"1", "Mixed arithmetic",
         "An int meeting a double makes the whole expression a double.",
         "Where a calculation turns decimal decides what it keeps."},
        {"1", "Casting",
         "Converting a value to another type on purpose: (int), (double).",
         "(int) cuts off, it does not round. 99.7% becomes 99."},
        {"1", "long",
         "A whole-number type with a far larger range than int.",
         "Byte counts and timestamps outgrow an int quickly."},
        {"1", "Integer overflow",
         "Going past a type's largest value wraps round to its smallest.",
         "A counter that wraps negative resets a rate limit silently."},
        {"1", "length()",
         "Asks a String how many characters it holds.",
         "A 400-character username is a probe, not a person."},
        {"1", "Strings do not change",
         "String methods hand back a new String. The old one is untouched.",
         "A sanitising call whose result is ignored sanitises nothing."},
        {"1", "trim()",
         "Removes spaces from both ends of a String.",
         "\"admin \" and \"admin\" must not become two accounts."},
        {"1", "charAt()",
         "Returns the single character at a position.",
         "Pulling a flag out of a fixed position in a log line."},
        {"1", "Indexes start at 0",
         "The first character is at 0, the last at length() - 1.",
         "Off-by-one reads are how parsers crash on hostile input."},
        {"1", "substring()",
         "Cuts out part of a String. The end position is not included.",
         "Fixed-width log parsing, and why it is fragile."},
        {"1", "Scanner",
         "Reads what is typed at the keyboard, a line at a time.",
         "Everything typed is untrusted until your code has checked it."},
        {"1", "Integer.parseInt",
         "Turns text such as \"443\" into the int 443.",
         "Text that is not a number crashes it. Input decides uptime."},
        {"1", "Math methods",
         "Math.max, Math.min and Math.abs.",
         "Clamping an untrusted number into a safe range."},
        {"1", "Math.round",
         "Rounds to the nearest whole number, and hands back a long.",
         "Rounding on purpose instead of truncating by accident."},
        {"1", "indexOf()",
         "Finds where text first appears in a String, or -1 if nowhere.",
         "-1 used as a position quietly returns the wrong field."},
        {"1", "contains()",
         "Asks whether some text appears anywhere in a String.",
         "The simplest indicator match - and the easiest to evade."},
        {"1", "startsWith() and endsWith()",
         "Ask whether a String begins or ends with some text.",
         "invoice.pdf.exe ends with .exe, whatever it looks like."},
        {"1", "replace()",
         "Hands back a copy with every match swapped for something else.",
         "Neutralising line breaks stops forged log entries."},
        {"1", "printf",
         "Prints text with placeholders filled in and formatted.",
         "A report in straight columns gets read. A ragged one gets skimmed."},
        {"1", "Parsing a log line",
         "Cutting a structured line into typed fields.",
         "The first thing every detection tool does with its input."},

        {"2", "Comparison operators",
         "==, !=, <, >, <= and >=. Each gives true or false.",
         "Every detection rule is a comparison underneath."},
        {"2", "if",
         "Runs a block only when its condition is true.",
         "Always write the braces. goto fail is why."},
        {"2", "Short-circuit evaluation",
         "&& stops at the first false, || at the first true.",
         "Put the guard on the left: check, then use."},
        {"2", "if / else",
         "Runs one block or another depending on a test.",
         "Every access decision is an if at the bottom of it."},
        {"2", "if / else if / else",
         "A chain of tests, stopping at the first true one.",
         "Severity grading: critical before warning before normal."},
        {"2", "Boundary conditions",
         "The value where a rule changes its answer.",
         "Off-by-one in a lockout gives an attacker an extra guess."},
        {"2", ">= vs >",
         "Whether the threshold value itself counts.",
         "'5 or more' and 'more than 5' are different policies."},
        {"2", "Logical operators",
         "&& means both, || means either, ! means not.",
         "Translating a written policy into a condition."},
        {"2", "Comparing decimals",
         "0.1 + 0.2 is not exactly 0.3. Compare doubles within a tolerance.",
         "Money and scores stored as doubles drift; totals stop matching."},
        {"2", "Character methods",
         "Character.isDigit, isLetter, isUpperCase and friends.",
         "Checking what kind of character arrived before trusting it."},
        {"2", "Nested if",
         "An if inside another if. else belongs to the nearest if.",
         "Misread nesting is how a check guards the wrong branch."},
        {"2", "Validating input",
         "Checking text is what you expect before converting or using it.",
         "An allowlist pattern rejects everything you did not plan for."},
        {"2", "isEmpty and isBlank",
         "isEmpty: no characters. isBlank: nothing but spaces.",
         "A username of three spaces is not a username."},
        {"2", "Scope",
         "A variable exists only inside the block where it is declared.",
         "A value set in one branch and read after the if may not exist."},
        {"2", "The conditional operator",
         "condition ? valueIfTrue : valueIfFalse - an if that gives a value.",
         "Short labels, clear defaults. Nested, it hides logic."},
        {"2", "switch",
         "Chooses a branch by matching one value against exact cases.",
         "A missing break falls through - and can grant a lower role more."},
        {"2", "Switch expressions",
         "switch with -> that produces a value. No fall-through.",
         "Must cover every case, so no value slips through unhandled."},
        {"2", "De Morgan's laws",
         "!(a && b) is !a || !b, and !(a || b) is !a && !b.",
         "Turning an allow rule into its deny rule without a gap."},
        {"2", "String comparison",
         "Comparing text with .equals(), never with ==.",
         "== on a password check is a real and common vulnerability."},
        {"2", ".equals()",
         "Asks whether two objects hold the same contents.",
         "The only correct way to compare credentials."},
        {"4", "while loop",
         "Repeats a block while its test stays true.",
         "Log files have thousands of lines. You will not read them by hand."},
        {"4", "Counters",
         "A variable that counts how many times something happened.",
         "Detection is mostly counting, then comparing to a threshold."},
        {"4", "Loop update",
         "The step in the body that moves a loop towards its end.",
         "Exponential back-off is just an update that doubles."},
        {"4", "Infinite loops",
         "A loop whose condition never becomes false.",
         "Crafted input that loops a server for ever is a denial of service."},
        {"4", "Sentinel values",
         "A special input, like done or -1, that means stop reading.",
         "Every protocol must ask: what if the stop marker never comes?"},
        {"4", "Off-by-one errors",
         "A loop that runs one pass too many or too few.",
         "Six guesses where the policy allows five."},
        {"4", "for loop",
         "A loop with its start, test and update in one header.",
         "Read the header and you know the whole range a script will touch."},
        {"4", "Looping over a String",
         "Visiting positions 0 to length() - 1 with charAt.",
         "How a program sees adm1n where a person reads admin."},
        {"4", "Accumulators",
         "A running total that adds each value as it arrives.",
         "Slow data theft only shows up when it is all added together."},
        {"4", "Maximum and minimum",
         "Keeping the biggest and smallest value seen so far.",
         "Averages smooth attacks away; the maximum points at them."},
        {"4", "do-while loop",
         "A loop that runs its body first and tests afterwards.",
         "Prompts and heartbeats must happen before anything is tested."},
        {"4", "Input retry loops",
         "Ask, validate, ask again - until valid or out of tries.",
         "A retry limit is what stops a guessing script."},
        {"4", "break",
         "Leaves the innermost loop at once.",
         "A scanner stops at the first matching signature."},
        {"4", "continue",
         "Skips the rest of one pass; the loop carries on.",
         "A parser that skips too eagerly can be told to ignore a rule."},
        {"4", "Nested loops",
         "A loop inside a loop; the passes multiply.",
         "Every extra password character is another nested loop."},
        {"4", "Choosing a loop",
         "for for a known range, while for unknown, do-while for once+.",
         "A loop whose end is obvious is a loop a reviewer can trust."},
        {"4", "Loops and methods",
         "The loop picks the items; a method decides about one.",
         "Detection engines loop over events and call small rules."},
        {"4", "Character counting",
         "Classifying every character with an else-if chain.",
         "Powers password meters - where length should weigh most."},
        {"4", "Linear search",
         "Checking items in order until the first match, or none.",
         "Finding the first character that has no business in a name."},
        {"4", "Key space",
         "How many possible secrets exist: choices to the power length.",
         "Strength is key space and rate - lockouts slow the rate."},
        {"4", "Lockout logic",
         "Failures in a row, reset on success, locked at a limit.",
         "Check the lock first, or a locked account still answers."},
        {"4", "Rate limiting",
         "At most N requests per time window; the rest wait.",
         "Turns a flood of guesses or requests into a trickle."},
        {"4", "Menu loops",
         "Show, read, act, repeat until exit - with a default case.",
         "Every menu option is a way in; check permissions in each."},
        {"4", "Loop guards",
         "Bounds check on the left of &&, the use on the right.",
         "Parsers that crash on odd input can be knocked over at will."},
        {"4", "Building output",
         "A String grown piece by piece, separators between items.",
         "Each piece added to output needs the right escaping."},
        {"4", "Tracing a loop",
         "A table: a column per variable, a row per condition check.",
         "Analysts trace loops in code they must never run."},
        {"4", "Loop bugs",
         "The checklist: bounds, exits, semicolons, state, guards.",
         "Code that looks right to a skimming reviewer may not be."},
        {"4", "Scanning input",
         "Read, skip noise, classify, count, flag, then summarise.",
         "The core of every log-monitoring rule."},
        {"4", "Range checks",
         "Asking a rule about every value in a range, and reporting.",
         "Turns a firewall config into the list of what is really open."},
        {"3", "Methods",
         "Named behaviour you write once and call by name.",
         "A rule written once cannot drift out of step with itself."},
        {"3", "void",
         "A method that does something rather than answering something.",
         "Printing a report hands nothing back."},
        {"3", "Method calls",
         "Running a method: jump in, run its body, come back after the call.",
         "Reading code - or malware - means following every call."},
        {"3", "Parameters",
         "A variable in a method's header that each call fills in.",
         "Every parameter is a door for outside data. Ask where it came from."},
        {"3", "Arguments",
         "The value a call hands to a method's parameter.",
         "The same method, pointed at a different host each time."},
        {"3", "Parameter order",
         "Arguments match parameters by position, never by name.",
         "Swapped same-type arguments compile - and break security checks."},
        {"3", "return",
         "Hands a value back to the caller and ends the method at once.",
         "A returned answer can feed a dashboard, an alert or a test."},
        {"3", "Return values",
         "The value a call becomes, once its method has returned.",
         "Deciding and acting can live in separate, checkable methods."},
        {"3", "Return types",
         "The type of value a method promises to hand back.",
         "A boolean answer has no third, misreadable value."},
        {"3", "Calls in conditions",
         "Using a returned value directly in an if, a sum or another call.",
         "Check once, act on what you checked: the TOCTOU lesson."},
        {"3", "Guard clauses",
         "Checking a bad case first and returning straight away.",
         "A check that warns but does not leave lets the attack through."},
        {"3", "Boolean methods",
         "Methods that answer a yes-or-no question, named like one.",
         "One validation rule, shared by every caller, correct everywhere."},
        {"3", "Method names",
         "Verbs for actions, questions for booleans, answers for values.",
         "Backdoors hide in methods with routine-sounding names."},
        {"3", "Local variables",
         "Variables that exist only inside their method, only while it runs.",
         "Data only its owner can change cannot be quietly corrupted."},
        {"3", "Pass by value",
         "A method gets a copy of each argument's value, never the variable.",
         "A counter updated in a copy never locks the account."},
        {"3", "Strings as arguments",
         "Text methods return new Strings, so text helpers must return too.",
         "A sanitiser whose result is dropped sanitises nothing."},
        {"3", "Overloading",
         "Several methods with one name and different parameter lists.",
         "Which version runs? Only one of them may be safe."},
        {"3", "Methods calling methods",
         "Building big methods from small named helpers, in layers.",
         "One logging method means one fix for log injection everywhere."},
        {"3", "The call stack",
         "Frames pushed by calls and popped by returns. The top one runs.",
         "Stack buffer overflows overwrite a frame's return address."},
        {"3", "Stack frames",
         "One call's parameters, locals and place to return to.",
         "Short-lived secrets belong in frames, gone at the return."},
        {"3", "Stack traces",
         "The call stack printed at a crash: what, where, and how.",
         "Log traces for developers; never show them to users."},
        {"3", "Recursion",
         "A method that calls itself, with a base case to stop.",
         "Deeply nested input can exhaust a recursive parser."},
        {"3", "StackOverflowError",
         "Thrown when frames pile up until the stack has no room.",
         "A denial of service from nothing but nesting."},
        {"3", "Class constants",
         "static final values in the class, shared by every method.",
         "One lockout threshold, one answer, on every path."},
        {"3", "Static fields",
         "Changeable class variables that last for the whole program.",
         "Every method that can write shared state can lift a lockdown."},
        {"3", "Decomposition",
         "Splitting a job into steps, one small method per step.",
         "One reviewed rule instead of three slightly different copies."},
        {"3", "Testing a method",
         "Calling it with known inputs and comparing to expected results.",
         "Security testing proves the bad input is refused."},
        {"3", "Documentation comments",
         "/** comments stating a method's contract: @param and @return.",
         "Unstated assumptions become holes when code is reused."},
        {"3", "Refactoring",
         "Changing how code is organised without changing what it does.",
         "Paying down security debt, one verified step at a time."},
        {"3", "Validation helpers",
         "A shared set of small validators, combined with &&.",
         "Validate at the boundary, against an allow-list."},
        {"3", "Fail fast",
         "Every guard at the top, in a deliberate order, returning early.",
         "A locked account must not answer password guesses."},
        {"3", "Fail closed",
         "Success only past every check; anything unexpected is refused.",
         "Failing open is how access controls get bypassed."},
        {"3", "Output sanitising",
         "Making a value safe for where it is going, such as a log.",
         "Line breaks in input can forge whole log entries."},
        {"3", "Designing a toolkit",
         "Small single-job helpers, combined by a method that reads as policy.",
         "Each piece reviewed once; defence in depth by design."},
        {"5", "Arrays",
         "A fixed number of values of one type, under one name.",
         "A batch of log entries, read together."},
        {"5", "Array length",
         "How many items an array holds. The last position is length - 1.",
         "Reading past the end crashes the parser."},
        {"5", "Creating arrays",
         "new int[size] for empty slots, or { } with starting values.",
         "Sizes taken from input need a sensible maximum."},
        {"5", "Default values",
         "0, 0.0, false - and null for Strings - until a slot is set.",
         "A null where a value was expected crashes the service."},
        {"5", "Looping over arrays",
         "for (int i = 0; i < a.length; i++) visits every slot.",
         "Batch analysis: every reading, every count, every host."},
        {"5", "Enhanced for",
         "for (int x : a) hands you every value in turn, with no index.",
         "No index means no off-by-one: every entry is visibly checked."},
        {"5", "ArrayIndexOutOfBoundsException",
         "The crash when an index is below 0, or length or more.",
         "Java refuses to read past the end - the bug behind Heartbleed."},
        {"5", "Arrays of Strings",
         "String[]: many pieces of text. Slots start null; compare with equals.",
         "Usernames, hosts and log fields, checked against a rule."},
        {"5", "Arrays as parameters",
         "A method can take an array, and return a new one.",
         "One tested helper analyses any batch - even an empty one."},
        {"5", "References",
         "An array variable holds where the array is; = copies that, not it.",
         "A 'backup' made with = shares the evidence it should protect."},
        {"5", "Copying arrays",
         "A new array with the same values: Arrays.copyOf(a, a.length).",
         "Never work on the original evidence - clean a copy."},
        {"5", "Arrays.toString",
         "Turns an array into text like [3, 0, 7] for printing.",
         "Seeing the whole array at once makes bugs easy to spot."},
        {"5", "Linear search",
         "Check each slot in turn; return at the first match, -1 after.",
         "Blocklists and watchlists: every entry must really be checked."},
        {"5", "Max, min and average",
         "Start from a[0], one pass, and divide as a double.",
         "A baseline of normal activity; spikes above it are alerts."},
        {"5", "Tally arrays",
         "An array of counters where the value is the index: t[v]++.",
         "Logins per hour, errors per code - a picture of the events."},
        {"5", "Parallel arrays",
         "Two arrays where the same index describes the same item.",
         "Out of step, they pin the evidence on the wrong account."},
        {"5", "Two-dimensional arrays",
         "An array of rows: g[r][c]; g.length rows, g[r].length columns.",
         "Day-by-hour and host-by-port grids make scans stand out."},
        {"5", "split",
         "Cuts a String at a separator into a String[]; dots need \\\\.",
         "Check parts.length: malformed lines are sent to crash parsers."},
        {"5", "ArrayList",
         "A list that grows as you add to it.",
         "A watchlist does not know its final size this morning."},
        {"5", "get and set",
         "Read or replace the item at an index; add(i, x) inserts.",
         "An incident queue in the wrong order is an incident handled late."},
        {"5", "remove, contains and indexOf",
         "Built-in searches using equals; remove takes the first match.",
         "Revoking access must remove every entry, and prove it."},
        {"5", "Looping over an ArrayList",
         "Either loop reads; to remove, loop backwards from size() - 1.",
         "A clean-up that skips entries leaves expired sessions alive."},
        {"5", "Wrapper classes",
         "Integer, Double, Boolean: objects holding one primitive value.",
         "== on Integers passes small tests and fails in production."},
        {"5", "The remove(int) trap",
         "On a list of Integers, remove(1) removes INDEX 1, not the value 1.",
         "The wrong rule vanishes and the right one stays open."},
        {"5", "Arrays or ArrayList",
         "Arrays for fixed sizes and grids; lists for data that grows.",
         "A full array drops alerts; an endless list runs out of memory."},
        {"5", "Sorting",
         "Arrays.sort and Collections.sort, in place, smallest first.",
         "A log's order is its timeline: sort a copy, keep the original."},
        {"5", "Watchlists",
         "A list with rules: normalised names, no duplicates, a cap.",
         "Stored and searched spellings must match, or suspects go unseen."},
        {"5", "Removing duplicates",
         "Build a new list, adding each value only if not yet present.",
         "Distinct sources and targets tell spraying from a typo."},
        {"5", "Counting per key",
         "Two growing lists in step: names, and a count at the same index.",
         "Top offender lists start most investigations."},
        {"5", "Allowlists",
         "Deny by default; allow only exact, normalised matches.",
         "Loose matching lets look-alike domains walk straight in."},
        {"6", "Classes",
         "A description of what something is like.",
         "A log event has a shape. Describe it once."},
        {"6", "Objects",
         "One actual thing built from a class, using new.",
         "One object per log line, per account, per host."},
        {"6", "Fields",
         "The values an object holds.",
         "The parts of a log line, kept separate and typed."},
        {"6", "new",
         "Builds an object. Naming a variable does not.",
         "Two accounts need two objects, or they share one state."},
        {"6", "The dot operator",
         "obj.field reads or writes a field; chains read left to right.",
         "Lockout state lives in its object: acct.fails++, acct.locked."},
        {"6", "Object references",
         "An object variable holds where the object is; = copies that.",
         "A shared session or permission object leaks between users."},
        {"6", "null and NullPointerException",
         "null means no object; using the dot on it crashes.",
         "A request for something missing should not crash the service."},
        {"6", "Instance methods",
         "Methods without static, called on an object, using its fields.",
         "One lockout rule inside the class, not four copies outside."},
        {"6", "this",
         "The object a method runs on; this.x = x sets the field.",
         "A setter that silently does nothing leaves old values in force."},
        {"6", "Constructors",
         "Runs during new; same name as the class, no return type.",
         "An object that cannot exist half-built is never used half-built."},
        {"6", "The default constructor",
         "Java's free no-argument constructor - gone once you write one.",
         "Only allow an empty object when an empty one is safe."},
        {"6", "Constructor overloading",
         "Several constructors with different parameter types.",
         "Defaults like session length live in the class, set once."},
        {"6", "Constructor chaining",
         "this(...) as a constructor's first line calls another one.",
         "Every way of making an object passes the same validation."},
        {"6", "Getters and setters",
         "getX, isX and setX: the doors into private fields.",
         "Each setter is attack surface; offer operations, not raw access."},
        {"6", "Validating setters",
         "Setters that refuse bad values keep every object valid.",
         "Validate at the object's own door: no caller can skip it."},
        {"6", "toString",
         "public String toString(): how an object becomes text.",
         "Objects end up in logs. Never put secrets in toString."},
        {"6", "equals for objects",
         "public boolean equals(Object o): same contents, not same object.",
         "Wrong equality makes allowlists allow nothing - or anything."},
        {"6", "Static and instance members",
         "static: one copy for the class. Instance: one per object.",
         "A static 'current user' leaks one user's identity to another."},
        {"6", "Lists of objects",
         "ArrayList<Account>: whole records, held as references.",
         "Changing a record read from the list changes the stored one."},
        {"6", "private",
         "A field only its own class can touch.",
         "A password nothing outside can read cannot leak by accident."},
        {"6", "Encapsulation",
         "Hiding data and exposing only what is safe to ask.",
         "A security control, not just tidiness."},
        {"7", "Exceptions",
         "A failure that stops the program unless it is caught.",
         "One malformed log line should not end the overnight run."},
        {"7", "try / catch",
         "Runs risky work, and handles the failure if it comes.",
         "A parser that survives bad input keeps monitoring alive."},
    };

    /** For CheckAll: every topic, as campaign | name | definition | why. */
    public static String[][] topics() {
        return TOPICS;
    }

    public static void show(Player player) {
        Terminal.newScreen();
        Terminal.rule('+', '=');
        Terminal.centred("JAVA KNOWLEDGE");
        Terminal.rule('+', '=');

        int known = 0;
        int shown = 0;
        int hidden = 0;
        for (Campaign campaign : CampaignIndex.all()) {
            String number = String.valueOf(campaign.getNumber());
            if (!campaign.isBuilt()) {
                for (String[] topic : TOPICS) {
                    if (topic[0].equals(number)) {
                        hidden = hidden + 1;
                    }
                }
                continue;
            }
            Terminal.blank();
            Terminal.line("  " + campaign.getLabel());
            for (String[] topic : TOPICS) {
                if (!topic[0].equals(number)) {
                    continue;
                }
                boolean learned = player.hasLearned(topic[1]);
                if (learned) {
                    known = known + 1;
                }
                shown = shown + 1;
                Terminal.line("    " + (learned ? Theme.paint(Theme.GOOD, "[x]") : "[ ]")
                        + " " + topic[1]);
            }
        }

        Terminal.blank();
        Terminal.line("  " + known + " of " + shown + " topics learned.");
        if (hidden > 0) {
            Terminal.line("  " + hidden + " more arrive with campaigns not yet built.");
        }
        Terminal.blank();
        Terminal.wrapped("A topic is ticked once you complete a mission that "
                + "teaches it.", "  ");
        Terminal.blank();

        String choice = Terminal.ask("  Type a topic name to read about it, or ENTER to go back: ");
        if (choice.isEmpty()) {
            return;
        }
        showTopic(choice);
    }

    private static void showTopic(String name) {
        for (String[] topic : TOPICS) {
            if (topic[1].equalsIgnoreCase(name.trim())) {
                Terminal.newScreen();
                Terminal.heading(topic[1].toUpperCase());
                Terminal.blank();
                Terminal.wrapped("WHAT IT IS", "  ");
                Terminal.wrapped(topic[2], "    ");
                Terminal.blank();
                Terminal.wrapped("WHY IT MATTERS IN SECURITY", "  ");
                Terminal.wrapped(topic[3], "    ");
                Terminal.blank();
                Terminal.wrapped("TAUGHT IN", "  ");
                for (String missionId : missionsTeaching(topic[1])) {
                    Terminal.line("    " + missionId);
                }
                Terminal.blank();
                Terminal.pause();
                return;
            }
        }
        Terminal.line("  No topic by that name.");
        Terminal.pause();
    }

    private static List<String> missionsTeaching(String topic) {
        List<String> found = new ArrayList<>();
        for (Mission mission : CampaignIndex.allMissions()) {
            for (String concept : mission.getWillLearn()) {
                if (concept.equalsIgnoreCase(topic)) {
                    found.add(mission.getId() + "  " + mission.getTitle());
                }
            }
        }
        if (found.isEmpty()) {
            found.add("(not yet covered by a mission)");
        }
        return found;
    }
}
